### ISSUE TITLE
Multiple repositoryFactoryBeanClasses: spring-data-envers and spring-data-jpa-datatables

### ISSUE THREAD

**Issue by dokle** [spring-projects/spring-data-envers#164]
In my company we use the extension "spring-data-jpa-datatables" and have to reference the "DataTablesRepositoryFactoryBean.class" as repositoryFactoryBeanClass. So how can we add spring-data-envers as an additional extension? The @EnableJpaRepositories annotation only allows a single reference as FactoryBean. How can we use both without splitting the repositories?

**Comment by schauder** [comment]
Please use the issue tracker only for issues, i.e. bugs and feature requests.
The proper place for help questions like this on is Stackoverflow.

That being said: `DataTablesRepositoryFactoryBean` looks fairly simple. 
It should be possible to reimplement it based on `EnversRevisionRepositoryFactoryBean`

**Comment by oswaels** [comment]
Hi, @dokle I solved it adding spring-data-envers as an additional extension, specifying the package where the repositories are located on the project structure using the basePackages attribute.

`@EnableJpaRepositories(repositoryFactoryBeanClass = EnversRevisionRepositoryFactoryBean.class, basePackages = { "**.revision" })`

This way was easy because I have my own spring-boot-starter that initialize my custom `@NoRepositoryBean` implementation, so I can add it as a dependency easily.

`@EnableJpaRepositories(repositoryFactoryBeanClass = MyCustomJpaRepositoryFactoryBean.class, basePackages = { "**.repository" })`

**Comment by miamilabs** [comment]
> specifying the package where the repositories are located on the project structure using the basePackages attribute

Can you post an example here. I am fighting same issue and could not find the solution to have DataTablesRepositoryFactoryBean and EnversRevisionRepositoryFactoryBean in same project.
